name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: Matrix Test of Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "macos-latest", "macos-10.15" ]
        python-version: [ 3.6, 3.7, 3.8, 3.9, '3.10' ]

    steps:

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test
        run: |
          brew install python3-tk
          python -c 'import tkinter; window=tkinter.Tk(className="matplotlib")'
